name: Trivy Scan
on:
  workflow_dispatch:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout code (Full Clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # <--- This forces a full clone of the repository history

      - name: Run Trivy (console output)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          format: "table"
          severity: "HIGH,CRITICAL"
          exit-code: "0"

      - name: Run Trivy (sarif generation)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: "fs"
          format: "sarif"
          severity: "HIGH,CRITICAL"
          output: "trivy-results.sarif"
          exit-code: "0"

      - name: Upload to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: "trivy-results.sarif"
